"""Add images and video_url to products

Revision ID: 6c59823c62f1
Revises: 174f045ba7ac
Create Date: 2026-02-16 00:37:47.859713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c59823c62f1'
down_revision: Union[str, None] = '174f045ba7ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_id', table_name='orders')
    
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.add_column('products', sa.Column('images', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('products', sa.Column('video_url', sa.String(), nullable=True))
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###


def upgrade() -> None:
    op.add_column('products', sa.Column('images', sa.String(), nullable=True))
    op.add_column('products', sa.Column('video_url', sa.String(), nullable=True))
    op.drop_column('products', 'image_url')  # se você quiser remover a coluna antiga

def downgrade() -> None:
    op.drop_column('products', 'images')
    op.drop_column('products', 'video_url')
    op.add_column('products', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###
