"""create orders and order_items

Revision ID: a40bd2fcc7b5
Revises: cf98ed7344c7
Create Date: 2026-02-02 01:18:47.280853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a40bd2fcc7b5'
down_revision: Union[str, None] = 'cf98ed7344c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
